INSERT INTO product (name, category, price, description)
VALUES 
('Baseball', 'baseball', 1, 'Single baseball. Great for playing catch.'),
('Baseball Bat', 'baseball', 15, 'Wooden bat for that old school feel.'),
('Baseball Glove', 'baseball', 20, 'Great glove for catching baseballs.'),
('Baseball Uniform', 'baseball', 45, 'The whole uniform for $45! What a steal.'),
('Soccer Ball', 'soccer', 20, 'Latest in soccer ball technology.'),
('Shin Guards', 'soccer', 5, 'Protect your shins!'),
('Goalie Gloves', 'soccer', 5, 'Great gloves for your goalie.'),
('Soccer Cleats', 'soccer', 30, 'Good cleats are essential for any player.'),
('Soccer Jersey', 'soccer', 35, 'Support your hometown team with this jersey.'),
('Tennis Ball', 'tennis', 1, 'Loved by dogs and people alike.'),
('Tennis Racket', 'tennis', 20, 'Great racket for playing tennis.'),
('Tennis Net', 'tennis', 100, 'Set up a game in your own backyard.'),
('Basketball', 'basketball', 10, 'Best shooting ball you can buy.'),
('Basketball Shoes', 'basketball', 50, 'Fasionable and usefull.'),
('Basketball Hoop', 'basketball', 200, 'Hoop in your driveway!'),
('Football', 'football', 10, 'Great for throwing on Thanksgiving.'),
('Football Pads', 'football', 80, 'Full padding for your body.'),
('Football Helmet', 'football', 50, 'Protect your head.'),
('Football Cleats', 'football', 30, 'Cleats with great traction.'),
('Running Shoes', 'running', 40, 'Very sleek, lightweight shoes.'),
('Running Shorts', 'running', 10, 'Short shorts.'),
('Lacross Ball', 'lacross', 3, 'Hard slick ball for lacross.'),
('Lacross Stick', 'lacross', 16, 'Stick with a net on the end.'),
('Lacross Pads', 'lacross', 55, 'Full pasds for playing lacross.'),
('Lacross Net', 'lacross', 123, 'Comes with 2 nets to set up a game.'),
('Hockey Puck', 'hockey', 5, 'Small puck for playing ice hockey.'),
('Hockey Stick', 'hockey', 20, 'Curved stick for playing ice hockey.'),
('Hockey Pads', 'hockey', 90, 'Full set of hockey pads.'),
('Hockey Net', 'hockey', 160, 'Comes with two nets to set up a game.'),
('Water Bottle', 'gear', 8, 'Holds water so you can stay hydrated.'),
('Socks', 'gear', 10, 'Pack of 3 pairs lightweight socks.'),
('Athletic Tape', 'gear', 5, 'Roll of strong athletic tape.'),
('Water Cooler', 'gear', 25, 'Holds 5 gallons of liquid.'),
('Ice Pack', 'gear', 12, 'For icing your injuries.'),
('Fishing Pole', 'fishing', 45, 'Pole for catching fish.'),
('Fishing Line', 'fishing', 5, 'Roll of fishing line, 100ft.'),
('Fake Worm', 'fishing', 3, 'Bait for fishing.'),
('Fake Minnow', 'fishing', 5, 'Bait for catching bigger fish.');

